### ISSUE TITLE
Cell selection state (for non-empty cells) should be more obvious

### ISSUE THREAD

**Issue by jtbandes** [getguesstimate/guesstimate-app#100]
Cell selection state for empty cells is very obvious:

![image](https://cloud.githubusercontent.com/assets/14237/13312843/829252e6-db4e-11e5-8ec0-6159ce49392f.png)

But too subtle for non-empty cells (disregarding the height change):

![image](https://cloud.githubusercontent.com/assets/14237/13312850/9465d146-db4e-11e5-84cd-780f32c7d855.png)

**Comment by OAGr** [comment]
I agree with this, not sure what the best way of doing this is.  Spent quite a while on it.  

Options, as I see it:
1) Color the background of the card
2) Put the blue border around the entire card
3) Blue border, only around the bottom. (the current state)

Do you prefer options **1** or **2**, or have any other ideas?

**Comment by jtbandes** [comment]
2) makes sense because it's consistent with the selected+empty cell state. I think 1) would probably be too subtle as wel.

**Comment by mmcdermott** [comment]
Agreed that 2) makes sense.

**Comment by OAGr** [comment]
One awkward thing about (2) is that it would effectively add an extra 4 pixels of width to each card, plus it's pretty intense.  I'll experiment with it.  Also, feel free to modify the CSS in browser and post pics of better versions.

**Comment by jtbandes** [comment]
What about something like this?

![selection](https://cloud.githubusercontent.com/assets/14237/13313369/2cf91a00-db52-11e5-8e93-90112a795189.gif)

**Comment by OAGr** [comment]
I guess my intuition for that was that it would imply the user is selecting the background; not the card.  That said, I'm not an expert at UI, would like others to weigh in on that.

**Comment by OAGr** [comment]
I think this proposal is worth a try

**Comment by OAGr** [comment]
How about this? 

## Alternative View
![alternative](http://g.recordit.co/t83BrsHr0R.gif)

## Current View (For Reference)
![current](http://g.recordit.co/Mn71wTvsEa.gif)

**Comment by jtbandes** [comment]
Not a huge fan of the sea-foam color, but I think it looks much nicer this way :)

Any chance of slightly animating the expansion of selected cells? (maybe just a simple CSS transition…) I think it's pretty distracting when they jump around as you move your selection.

**Comment by OAGr** [comment]
Yea, I think the green is a bit intense too.  I made it last night with flux on.  It's easy to dim; the bigger question is really if we want the background to be highlighted or if it should be more of the item-specific area.

I'd love an animation there.  Animations aren't something I'm great at.  I spent quite a while with it a few months back with that exact part but didn't have much luck, may try again sometime.  I don't believe it's a simple CSS transition because the hiding/showing isn't CSS, it's showing or hiding a React component.

**Comment by jtbandes** [comment]
The other option would be to simply not change the cell/row size when it's selected. I almost think it would be preferable (from a less-confusing-UX point of view), but I can see why you want to expand them too...

**Comment by OAGr** [comment]
Fair point.  If we didn't change the size, how would you see the input appearing?

**Comment by jtbandes** [comment]
Just brainstorming here: maybe instead of a "selected" state, you have an "editing" state. Selection would just be the cell background, and you'd have to enter edit-mode explicitly (e.g. by pressing enter). Then the cell could expand (it would be obvious what's going on in that case) or the input field(s) could even pop up/out without the cell itself changing size.

I think I'm subconsciously suggesting exactly what Excel and Google Sheets do, so take this with an extra grain of salt. ;)

**Comment by OAGr** [comment]
I tried doing that initially (a 'selected' and 'editing' state) and found it to be confusing.  One particular challenge is that seems like it would increase the learning curve for new users.  It is an option for the future though, but not an urgent one imo.
