### ISSUE TITLE
Firefox issue: Can't move cursor with mouse in cell

### ISSUE THREAD

**Issue by yalla** [getguesstimate/guesstimate-app#104]
When I want to edit a distribution or fixed value of a cell, the following happens:
1. Click in text field of cell
2. Cursor appears at random location in string
3. Can't mark text or move cursor with mouse click
4. When the text field has focus, I need to use the cursor buttons on my keyboard.

Reproducible: Always

Affected User Agents (verified):
* Firefox 44.0.2 / Linux x86_64
* Firefox 44.0.2 / OSX
* Firefox 45.0b / Android 5

Not affected:
* Any version of Google Chrome; they all work, on Linux, OSX and Android.

This behavior appeared some when in the last week, but it's possible that it's there ever since; I'm browser-agnostic and sometimes just don't care which I'm using.
I recorded a screencast, but unfortunately it didn't highlight mouse events. If you need it, I could put more effort into that.

**Comment by OAGr** [comment]
Thanks for looking into this.

**Comment by mmcdermott** [comment]
This has been fixed.
