### ISSUE TITLE
Get rid of magic constants in code

### ISSUE THREAD

**Issue by berekuk** [getguesstimate/guesstimate-app#1044]
At least for production; for dev, we can keep them in `.env.development` file.

**Comment by cochetti** [comment]
If "magic constants" are the city population sizes, I was just reading the docs and tried to access that feature. If you disabled them, please update the documentation.  Alternatively, just shove a few placeholders in for the public side like @fair.coin = 0.50, @earth.gravity = 9.81, and @us.population during the 2020 census or something. These are fixed values that won't need to be updated ever. It will seem like the feature is functional on both the public and private sides.
