### ISSUE TITLE
Suggestion: Remove docs landing page and link directly to docs/introduction 

### ISSUE THREAD

**Issue by cochetti** [getguesstimate/guesstimate-app#1057]
**Suggestion:** 
redirect documentation link to be: a) consistent, b) direct. 

**Implementation:** 
refactor such that the introduction page resides at docs.getguesstimate.com or bypass this level and link directly to docs.getguesstimate.com/docs/Introduction

**Alt. Implementation:** 
create an informative landing page with links to the intro, faq, etc for the docs.getguesstimate.com page and change the header link to provide consistent nav

**Current Issue:**
When on the model, pricing, or other pages of the website [www.getguesstimate.com](www.getguesstimate.com) there is a link on the header to "documentation".  Clicking that link takes one to a page with no information and no clear link to the actual documentation. There is little content and no documentation of the system at all. 

Only by clicking what appears to be the exact same header "documentation item does one then get directed to an introduction and a page that looks like traditional documentation. This click-pattern is unintuitive as it requires clicking the same link twice and getting two different outcomes. The traditional UX assumptions are that header and footer links are static across pages and will link to the same component of the page. 

**Screenshots:**
Click "documentation" the first time brings one here [docs.getguesstimate.com](https://docs.getguesstimate.com/):
![image](https://github.com/user-attachments/assets/66ca6133-c1a7-4291-bb2a-ff5028cf5efe)

Clicking "documentation" on this page then subsequently brings you here [https://docs.getguesstimate.com/docs/Introduction](https://docs.getguesstimate.com/docs/Introduction)
![image](https://github.com/user-attachments/assets/78933c0e-6083-4939-918e-a2e415e9570a)

**Comment by OAGr** [comment]
Changed!

**Comment by cochetti** [comment]
Fantastic!  And great system you have here... It took me a little while to figure out how it worked (in part because I couldn't find the directions at first). Once I found the instructions, it became really fun to explore. 

Also, this is just a side note to another issue #1004 that I explored a bit yesterday. It took me awhile to realize that "the big summary number" displayed was a mean. 

Once I started playing with function syntax and reviewing the quantiles (which is what I thought the requestor was speaking about at first), it slowly dawned on me that "the big summary number" was reflecting a meaningful quantity that wasn't just the sample size N. And actually having just spent another hour or so with the tool, as I prepared my suggestion below, I have been more and more blown away by how cool this project is. 

I initially was seeking out the documentation because I wanted to know how to input specific distributions for my input values. Today after your praise of my feedback, I decided to put together the below image as a suggestion that might help others out when first encountering your tool. Then, as I was putting together my image, I kept discovering more features of the system when I would recognize things like "there must be a reason this squiggle is here".  You had already thought of distribution handling and baked it in the tool. 

I will fully admit that I didn't read thoroughly through the docs after having spent awhile typing up my issue report about my journey to finding them. That said, today, I did put this suggestion together to help others who may not fully read everything. Your system is super intuitive, and it's super dense with features. 

Would it be possible to add a graphic such as this one as a summary explainer of as many features as I could fit in a single image: 

![guesstimate_explainer](https://github.com/user-attachments/assets/13073382-02fe-4e4f-962f-be750f516828)
[guesstimate_explainer.zip](https://github.com/user-attachments/files/18030697/guesstimate_explainer.zip)

I am attaching the Photoshop file in a zip file to this comment if you want to change anything on the image. I have a rather huge monitor so I suspect that at a more reasonable scale the text descriptions may not be legible. Let me know and I can turn those off and upload another version of this image (if you don't have Photoshop or a suitable alternate editor). 

p.s. There's just one other thing that I might suggest. Have you considered adding a rounded rectangle around the distribution squiggle to make it a slight bit more obvious that it is a button. (You might give it a slight 15% gray to help suggest its button-ness as well.)

p.p.s. Actually one other just slight thing, but this one is probably more long term... You may just want to put N=5000 on there (possibly by the quantiles/percentiles) as I kept finding myself wondering how large the sampling was when I was using the function input.

**Comment by Mikael-Thorup** [comment]
Hi @cochetti, nice feedback! I think perhaps your latest message was not seen, e.g. since the PR was closed already. if I was you I'd consider creating a new issue, as I think your feedback is good for avoiding confusion and ensuring new users quickly see the value of the tool
