### ISSUE TITLE
Copy a Card

### ISSUE THREAD

**Issue by OAGr** [getguesstimate/guesstimate-app#116]
This should rely on the json metric functionality.  So when you copy & paste a metric, it copies everything, except possibly the ID and readableId.

**Comment by OAGr** [comment]
One of these should be used for the copy event:
https://github.com/greenify/copy2clipboard
https://github.com/jonschlinkert/to-clipboard

**Comment by mmcdermott** [comment]
We now support cut, copy, and paste.
