### ISSUE TITLE
Browser Test

### ISSUE THREAD

**Issue by OAGr** [getguesstimate/guesstimate-app#148]
Test editing in Firefox and Safari

**Comment by yalla** [comment]
Do you have a pre-production environment? I could help a little, if you need a hand.

**Comment by OAGr** [comment]
For something like this (and most things that don't require signing in), I would recommend running the client against the production server.  This would mean you wouldn't need to get the rails server set up locally.

Just clone the app and try running it (``npm install; npm run start``).  This will lead to a few node module issues that need to get resolved in the node_modules directory now, but once that is dealt with it should run fine.  I realize that this may be a deal breaker though; depending on your machine it may not be that fun.

I may be able to set it up in a docker container fairly easily, but that would require people to set that up, which may not be that much easier.
