### ISSUE TITLE
Documentation sidebar in HEAD missing

### ISSUE THREAD

**Issue by yalla** [getguesstimate/guesstimate-app#165]
The documentation button/sidebar is missing since a few days. I did a little git bisect work and found the offending commit:

```
$ git bisect bad
279f580ecbe6fd225f610f076c41aa423a84fe2f is the first bad commit
commit 279f580ecbe6fd225f610f076c41aa423a84fe2f
Author: Matthew McDermott <mattmcdermott8@gmail.com>
Date:   Mon Mar 7 22:38:13 2016 -0800

    Fixing curly brace.

    :040000 040000 9e2504216de7096010e51a7961ba54183d6f2609
    9b4169b579ed450e443ad164bb43af7d48d3f3bd M  src
```

The last working state is available in commit `cd11cee448d7a082cad7671d773a0153991398db` ("Refactored MetricModal to separate PercentileTable").

**Comment by yalla** [comment]
Sorry, but... is it possible that the documentation is fetched from some kind of remote server? It spontanesouly started working again. If yes, close and sorry for the hassle.

**Comment by mmcdermott** [comment]
Yep, indeed it is! Thanks for following up on this regardless, though.

**Comment by OAGr** [comment]
Yep, we're using Elev.io for documentation
