### ISSUE TITLE
Sampling is inaccurate especially for log-normal distributions

### ISSUE THREAD

**Issue by michaeldickens** [getguesstimate/guesstimate-app#184]
I refreshed a model four times and got these four different results. The results vary by more than an order of magnitude. I believe this tends to happen more with log-normal distributions than with other kinds of distributions.

![screen shot 2016-03-14 at 11 27 35 am](https://cloud.githubusercontent.com/assets/414378/13755350/13852f66-e9d8-11e5-90ed-fc54cf7d33fc.png)
![screen shot 2016-03-14 at 11 27 47 am](https://cloud.githubusercontent.com/assets/414378/13755353/138a36fa-e9d8-11e5-91f1-cd70a4bc565c.png)
![screen shot 2016-03-14 at 11 27 53 am](https://cloud.githubusercontent.com/assets/414378/13755352/1388bcee-e9d8-11e5-8363-aa86390b6a33.png)
![screen shot 2016-03-14 at 11 28 08 am](https://cloud.githubusercontent.com/assets/414378/13755351/1387aff2-e9d8-11e5-94a1-e663310e4e2a.png)

**Comment by OAGr** [comment]
Basically, what seems to be happening isn't a specific bug as much as it is a challenge of having long tails with monte carlo sampling, especially for relatively small sample counts.  The numbers visible on this dashboard the means, which vary greatly depending on outliers.  If you investigate this further I would bet that the medians are closer together.  Also, it looks like the confidence intervals don't change much.

I think this presents a few options:
1) Show medians, not means on this page.
2) More samples everywhere.
3) More samples, specifically in these situations.
4) Warnings where the value is highly outlier-sensitive.

**Comment by OAGr** [comment]
There are likely a few things to consider regarding this model.

BEWARE when dividing be a wide normal distribution. This typically presents cases where you divide by 0, or divide by something close to 0, which is a big outlier. Changing spending to be lognormal probably makes more sense, then much of this problem seems fixed.

**Comment by OAGr** [comment]
We now use a 'X to Y' syntax, which addresses this issue.
