### ISSUE TITLE
Save button doesn't always work

### ISSUE THREAD

**Issue by OAGr** [getguesstimate/guesstimate-app#2]
To reproduce:
- Go to ``http://www.getguesstimate.com/``
- Click on 'Foobar is pretty cool though'
- Move a node
- Press 'save'

**Comment by haryshwaran** [comment]
Save button does not work because there is invalid data in firebase. Value for one of the nodes is empty.
Things to do
1.This exception has to be handled.
2.Need to find out how the node had an empty value in the first place. ( try to reproduce this error in a new repo )

**Comment by OAGr** [comment]
How do you think we should handle that?  i image we may not know that it's an exception until after we try saving a second time.
