### ISSUE TITLE
Ensure distribution shape is fully visible (and not lost due to long tails)

### ISSUE THREAD

**Issue by OAGr** [getguesstimate/guesstimate-app#219]
![image](https://zube.io/files/getguesstimate/ebddbc98b09e204ff2d14121aa90c948.png)

This looks crummy.  The outliers should be removed for both the card view and the expanded view.  This may be the top 1%, the top 5%, or so on, I'm not sure.

**Comment by mmcdermott** [comment]
Whatever we do here, we should keep it consistent across all distributions; i.e. I would say we shouldn't do any dynamic re-sizing of the graph or the picture will lose meaning across distributions; If we want to cut off at 95% then we should do that always, I would say.

But, that's less motivated by looks and more for ease of recognition of when your distribution has a long tail and when it doesn't, which may not be as important to others.

**Comment by OAGr** [comment]
Agreed.  This is necessitated by the frequency of lognormals, but it will apply to everything.
