### ISSUE TITLE
Sometimes metric descriptions don't get saved

### ISSUE THREAD

**Issue by OAGr** [getguesstimate/guesstimate-app#236]
A few times with this model, I would edit the description of 'Total Market Captured', but it wouldn't get saved for some reason.  There were no errors, it would just reset to the text before I clicked 'save' on it.

https://www.getguesstimate.com/models/4605

**Comment by mmcdermott** [comment]
The changeGuesstimate action is getting triggered occasionally (no obvious pattern) on modal close, with the previous value of the description in the 'changed value' thus overwriting the set description.

**Comment by mmcdermott** [comment]
It is the changeGuesstimateForm doing the calling of this.

**Comment by mmcdermott** [comment]
Here is the flow:

You open modal, enter description, click save. 
_changeGuesstimateDescription -> handleChangeGuesstimate -> changeGuesstimate (action)

Then, you close the card and:
_handleBlur -> handleSave (w/ empty Params) -> changeGuesstimateForm -> changeguesstimate (action) -> overwrites description.

**Comment by mmcdermott** [comment]
Here is the flow:

You open modal, enter description, click save. 
_changeGuesstimateDescription -> handleChangeGuesstimate -> changeGuesstimate (action)

Then, you close the card and:
_handleBlur -> handleSave (w/ empty Params) -> changeGuesstimateForm -> changeguesstimate (action) -> overwrites description.

**Comment by mmcdermott** [comment]
Here is the flow:

You open modal, enter description, click save. 
_changeGuesstimateDescription -> handleChangeGuesstimate -> changeGuesstimate (action)

Then, you close the card and:
_handleBlur -> handleSave (w/ empty Params) -> changeGuesstimateForm -> changeguesstimate (action) -> overwrites description.

**Comment by mmcdermott** [comment]
Here is the flow:

You open modal, enter description, click save. 
_changeGuesstimateDescription -> handleChangeGuesstimate -> changeGuesstimate (action)

Then, you close the card and:
_handleBlur -> handleSave (w/ empty Params) -> changeGuesstimateForm -> changeguesstimate (action) -> overwrites description.
