### ISSUE TITLE
Display issues in Edge

### ISSUE THREAD

**Issue by tathamoddie** [getguesstimate/guesstimate-app#42]
Edge 25.10586.0.0

The editing surface does not expand the cells as expected, making them unusable:

<img width="606" alt="guesstimate in edge 25 10586 0 0" src="https://cloud.githubusercontent.com/assets/45753/12070870/a418145a-b0e2-11e5-8c7e-03b7ab56b77d.png">

**Comment by OAGr** [comment]
Good to know.  This issue also seems to exist for mobile browsers.

Guesstimate uses both Semantic CSS and flexbox grid.  I've had some trouble with them, especially for cross-browser/mobile issues.  Considering going back to Bootstrap, but that would be a lot of work.

**Comment by OAGr** [comment]
I believe this should be fixed by now.  If it isn't please let us know.
