### ISSUE TITLE
Support peta prefix

### ISSUE THREAD

**Issue by plajjan** [getguesstimate/guesstimate-app#44]
I'm dealing with lots of numbers in the peta range but it switches over from Tera to 10^15 when passing 1000 tera. Could we have it as peta instead? :)

**Comment by OAGr** [comment]
We don't write out the names, just the letters.  So that would be 1P.  Personally, if I saw a number saying '30P', I would be confused.  Does anyone else have an opinion here?

**Comment by plajjan** [comment]
Yes, I meant 'P' and not actually peta. 

Perhaps it is confusing. Being a network / computer person I find it's rather natural with the metric prefixes kilo, mega, giga, tera, peta, exa prefixes.

I see that 10^9 is called 'B', presumably for billion. I was never a fan of that as it's somewhat ambiguous (short vs long scale) and means different things in different countries. SI prefix is (G)iga.

**Comment by OAGr** [comment]
That makes sense.

It used to be (G), then someone complained about it.  It probably would make sense to go all SI if we are choosing one, and have a hover over to explain.

**Comment by OAGr** [comment]
Added as 'discussion' because the bottleneck is the choice; not the functionality.
