### ISSUE TITLE
hacking information

### ISSUE THREAD

**Issue by paultag** [getguesstimate/guesstimate-app#47]
Some light information on how to set up a dev (or outward facing) deployment would be great!

**Comment by OAGr** [comment]
I'll need to add more here later, but here's a rough summary.

Guesstimate is a [Single Page Application](https://en.wikipedia.org/wiki/Single-page_application).  Everything in this repo is the client side, which is one reason why this is called 'guesstimate-app'.

There are two important third party systems.  Authentication is done with [Auth0](https://auth0.com/), and search/indexing is done with [Algolia](https://www.algolia.com/).  This means that running it yourself involves some setup, but on the other hand it's pretty easy set up compared to what you may need in comparable systems.  Both of these are free for moderate use.  I recommend both, though should note that the way I set up Algolia was a bit hacky (not sure how to do it right).  

There is also a small server in Rails, which is not yet on Github.  I'd like to work on security a bit more before putting it on here (if select people want to work on it I'd be happy to share in a small group).  However, this is quite tiny;  just 2 models (users, spaces).  

All models are stored and saved as 'spaces'.  The spreadsheet content is all stored as json in Postgres.  You can see the full requests if you look at the network tab in chrome.

However, while there are a few third party systems, everything will still work with just guesstimate-app, as long as you don't try to log in or save.  In practice this means that you can do quite a bit of development, as you can edit any model on the site (just can't save them).  It also makes much development quite simple when it's just on the website (not the server).  The line that controls this is here: 

``"start": "BUILD_DEV=0 NODE_ENV=development API_ENV=production webpack-dev-server"``

API_ENV=production (as opposed to development) means that it will use the production APIs.

**Comment by OAGr** [comment]
## How to run ( I think, can't try right now)

``git clone git@github.com:getguesstimate/guesstimate-app.git``
``cd guesstimate-app``
``npm install``
``npm run start``

There are often errors with specific things, but it depends on what is already installed on the computer.  Later we could put it in a docker container or something.

**Comment by OAGr** [comment]
I'm happy to answer specific questions as they are raised.  

In terms of the tech stack, the app is mostly React and Redux.  Most code in ``src``.  Most of it follows one or two organizational patterns, but it's a bit inconsistent in places, especially in the router lib and with regards to the stylesheets.  Would love to clean it up sometimes, but if people have specific concerns I would be happy to help there.

**Comment by paultag** [comment]
Sweet, thanks! I might formulate that into a HACKING markdown file :)

**Comment by OAGr** [comment]
For now I just put this in the README.md file
https://github.com/getguesstimate/guesstimate-app/blob/master/README.md

**Comment by rickyeasley** [comment]
U go Ozzie u fkg faggett

**Comment by rickyeasley** [comment]
OZ R U STILL MAD ABOUT ME FUNK ING UR GIRLFRIEND. I KNOW IT PROBABLY taste
a little funny when you kissed her but that's  just my way of saying u FK
WITH THE BULL BITCH U WILL GET THE HORNS

**Comment by OAGr** [comment]
Closing for now.  We could definitely improve what we have, but I believe this is sufficient for now.  If anyone wants more specific things, please say so.
