### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by kurtseifried** [getguesstimate/guesstimate-app#52]
$ cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 

running with latest d950de447ce508d301b1ebfc840a277dda502c01

ran npm install, installed a bunch of stuff, exited cleanly running npm run start:

Error: Cannot find module 'lodash.defaults'

so npm install lodash.defaults, repeat for autoprefixer 

these should probably be added as dependencies

**Comment by OAGr** [comment]
I've seen those as warnings a lot, it hasn't been a deal breaker.  This should obviously get fixed though.

**Comment by OAGr** [comment]
I think @haryshwaran dealt with this in PR https://github.com/getguesstimate/guesstimate-app/pull/64

Closing.
