### ISSUE TITLE
Generalizing Code for calling Uniform and Normal Distributions

### ISSUE THREAD

**Issue by davidmanheim** [getguesstimate/guesstimate-app#54]
In order to implement new distributions, it would be helpful to refactor and rewrite some of the code used for distributions.

- [ ] Include jStat Package
- [ ] Change distribution type to use 'param1', 'param2', etc. instead of 'mean', 'stdev' (uniform is also 2-parameter, it can use the same syntax and structure!)
- [ ] Also change validators to use new naming for parameters; only validator needed for normal; param2>0
- [x] (Check what else needs to be changed to allow this?)

- [ ] Replace code for Uniform distribution with jStat.uniform.sample(a, b)
- [ ] Allow direct specification of the jStat distribution name, so that it can be generalized easily.
- [ ] Use this as a template for Normal, so that it can be extended further (to other 2 parameter distributions, at least.)

**Comment by mmcdermott** [comment]
We now use jStat and nearly templated code for our distribution sampling, but this definitely could still use more refactoring. I'll post more updates here as things in this area improve further.

**Comment by mmcdermott** [comment]
The code in this section has undergone significant refactors and is now much more extensible. We also now support many additional distributions, and will handle requests for further distributions as they come.
