### ISSUE TITLE
Running a local version of guesstimate (for dev work, or otherwise...)

### ISSUE THREAD

**Issue by davidmanheim** [getguesstimate/guesstimate-app#55]
I'm setting up a local copy so I can test changes, etc.

It might be helpful to have a short walkthrough of how to do this for potential contributors.

1) You need node.js
2) Install package dependencies; run npm install from the root directory for guesstimate
3) ...

**Comment by davidmanheim** [comment]
You seem to need git installed as well.

**Comment by OAGr** [comment]
Semantic css needs to built as of now, which shouldn't be necessary as we aren't using any of the js. I'll mess with it, see if I can make that easier.

This process definitely needs to be cleaned up.

**Comment by paultag** [comment]
Related: #47

**Comment by rickyeasley** [comment]
Enjoy faggett

**Comment by davidmanheim** [comment]
OK, now I have all the node stuff installed, and I'm still unsure how to launch anything...

**Comment by haryshwaran** [comment]
@davidmanheim Visit localhost:3000 if its on you local system or if on a VM edit your hosts file and forward port 3000.

**Comment by davidmanheim** [comment]
In order to do that, I need to be running the node server. Which script
does that?

**Comment by haryshwaran** [comment]
<img width="949" alt="screen shot 2016-01-07 at 12 30 58 pm" src="https://cloud.githubusercontent.com/assets/5525738/12164301/92c9bada-b53a-11e5-9bbd-bb66682ad395.png">
Hope that helps. A few dependencies might be missing. The dependencies will be added soon. Meanwhile, you can install it using npm install --save [missing dependency] you will also need to build the semantic css.

**Comment by davidmanheim** [comment]
OK, next error set, from the NPM error log;

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program
Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@2.14.12
3 info using node@v4.2.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart guestimate@0.0.1
6 info start guestimate@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info guestimate@0.0.1 Failed to exec start script
9 verbose stack Error: guestimate@0.0.1 start: `BUILD_DEV=0
NODE_ENV=development API_ENV=production webpack-dev-server`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program
Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program
Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:211:5)
10 verbose pkgid guestimate@0.0.1
11 verbose cwd C:\[Install Directory Censored for Email]\Guesstimate
12 error Windows_NT 6.1.7601
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program
Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
14 error node v4.2.4
15 error npm  v2.14.12
16 error code ELIFECYCLE
17 error guestimate@0.0.1 start: `BUILD_DEV=0 NODE_ENV=development
API_ENV=production webpack-dev-server`
17 error Exit status 1
18 error Failed at the guestimate@0.0.1 start script 'BUILD_DEV=0
NODE_ENV=development API_ENV=production webpack-dev-server'.
18 error This is most likely a problem with the guestimate package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     BUILD_DEV=0 NODE_ENV=development API_ENV=production
webpack-dev-server
18 error You can get their info via:
18 error     npm owner ls guestimate
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by haryshwaran** [comment]
@davidmanheim could you please paste the whole error? it could be a missing dependency.
[ I saw you post an issue after this comment, have you got it running locally on the system. ]

**Comment by davidmanheim** [comment]
The npm-debug.log;

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@2.14.12
3 info using node@v4.2.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart guestimate@0.0.1
6 info start guestimate@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info guestimate@0.0.1 Failed to exec start script
9 verbose stack Error: guestimate@0.0.1 start: `BUILD_DEV=0 NODE_ENV=development API_ENV=production webpack-dev-server`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid guestimate@0.0.1
11 verbose cwd C:\[Install Directory]\guesstimate-app
12 error Windows_NT 6.1.7601
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
14 error node v4.2.4
15 error npm  v2.14.12
16 error code ELIFECYCLE
17 error guestimate@0.0.1 start: `BUILD_DEV=0 NODE_ENV=development API_ENV=production webpack-dev-server`
17 error Exit status 1
18 error Failed at the guestimate@0.0.1 start script 'BUILD_DEV=0 NODE_ENV=development API_ENV=production webpack-dev-server'.
18 error This is most likely a problem with the guestimate package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     BUILD_DEV=0 NODE_ENV=development API_ENV=production webpack-dev-server
18 error You can get their info via:
18 error     npm owner ls guestimate
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by ttriche** [comment]
fwiw, mine shits the bed when I try to run because of lodash:

tim@tim-ThinkPad-T450s:~/Dropbox/guesstimate-app$ npm run dev

> guestimate@0.0.1 dev /home/tim/Dropbox/guesstimate-app
> BUILD_DEV=1 NODE_ENV=development API_ENV=development webpack-dev-server


module.js:340
    throw err;
          ^
Error: Cannot find module 'lodash.defaults'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous>
(/home/tim/Dropbox/guesstimate-app/webpack-config/index.js:7:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! guestimate@0.0.1 dev: `BUILD_DEV=1 NODE_ENV=development
API_ENV=development webpack-dev-server`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the guestimate@0.0.1 dev script.
npm ERR! This is most likely a problem with the guestimate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     BUILD_DEV=1 NODE_ENV=development API_ENV=development
webpack-dev-server
npm ERR! You can get their info via:
npm ERR!     npm owner ls guestimate
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.2.0-23-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "run" "dev"
npm ERR! cwd /home/tim/Dropbox/guesstimate-app
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/tim/Dropbox/guesstimate-app/npm-debug.log
npm ERR! not ok code 0


--t

**Comment by davidmanheim** [comment]
Have you tried npm install lodash or npm install lodash.defaults?

**Comment by ttriche** [comment]
The former, yes; latter, no 

--t

**Comment by OAGr** [comment]
For the record, I think getting webpack and these dependencies working (somewhat) has been like 1/10th of the project for me so far.  It's a mess.  I'd spend more time on it now but have a lot of high urgency issues, and this does take some time.

**Comment by haryshwaran** [comment]
for now you can do `npm install lodash.defaults

**Comment by ttriche** [comment]
that helped, as did `npm install autoprefixer

but now it seems that node/v8/whatever is puking on ES6 template strings:

tim@tim-ThinkPad-T450s:~/Dropbox/guesstimate-app$ npm run dev

> guestimate@0.0.1 dev /home/tim/Dropbox/guesstimate-app
> BUILD_DEV=1 NODE_ENV=development API_ENV=development webpack-dev-server


/home/tim/Dropbox/guesstimate-app/webpack-config/lib/html-plugin.js:38
  add(`
      ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous>
(/home/tim/Dropbox/guesstimate-app/webpack-config/lib/base-config.js:2:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

npm ERR! guestimate@0.0.1 dev: `BUILD_DEV=1 NODE_ENV=development
API_ENV=development webpack-dev-server`
npm ERR! Exit status 8



any ideas appreciated; I was under the impression that node/v8 handled ES6
fine but apparently I was mistaken

--t

**Comment by haryshwaran** [comment]
@ttriche  you seem to be running v0.10.25. Would suggest you try in more recent versions.

**Comment by ttriche** [comment]
thank you -- that plus a few more dependency installs did it.


tim@tim-ThinkPad-T450s:~/Dropbox/guesstimate-app$ npm install rimraf
tim@tim-ThinkPad-T450s:~/Dropbox/guesstimate-app$ npm install lodash.assign
tim@tim-ThinkPad-T450s:~/Dropbox/guesstimate-app$ npm install find-root

and

tim@tim-ThinkPad-T450s:~/Dropbox/guesstimate-app$ npm run dev

> guestimate@0.0.1 dev /home/tim/Dropbox/guesstimate-app
> BUILD_DEV=1 NODE_ENV=development API_ENV=development webpack-dev-server

http://0.0.0.0:3000/webpack-dev-server/
webpack result is served from /
content is served from /home/tim/Dropbox/guesstimate-app/public
404s will fallback to /index.html



yay!


It does complain about some aspects of stochator but, realistically, that
part needs to be replaced with jStat anyways.




--t

**Comment by OAGr** [comment]
We removed much of the semantic.js dependency, it should be a bit easier now.

**Comment by mekarpeles** [comment]
@ttriche's recommendations worked for me.

**Comment by rfgoat2014** [comment]
Installed successfully on Digital Ocean VM! No errors during startup phase, Guesstimate URL opens up but console logs following errors:
:
GET https://assets.elev.io/wlocales/it/app.json
XMLHttpRequest cannot load https://assets.elev.io/wlocales/it/app.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://188.166.148.93:3000' is therefore not allowed access. The response had HTTP status code 404.
Uncaught TypeError: Cannot read property 'replace' of null

I tried modifying src/routes/app.js including:

app.use(function(req, res, next) { res.header('Access-Control-Allow-Origin', "http://http://188.166.148.93:3000/*"); res.header('Access-Control-Allow-Methods','GET,PUT,
POST,DELETE'); res.header('Access-Control-Allow-Headers', 'Content-Type'); next();
})

but it's still not working, any help?
tks

**Comment by OAGr** [comment]
This should be easier now, the Stochator lib has been removed, which caused a bunch of problems.

**Comment by OAGr** [comment]
Can someone else confirm that the problems seem not to happen any more?  I imagine there will be some problems for some people out there (it's difficult to get installation to be perfect), but I believe it should be good for most users now.

**Comment by OAGr** [comment]
Closing, this issue seems to be resolved at this point.
