### ISSUE TITLE
Color backgrounds of cells

### ISSUE THREAD

**Issue by OAGr** [getguesstimate/guesstimate-app#56]
From a request,
"Just wanted to see if there was a way to color (fill or outline) cells? Would be great to have this feature to highlight different cells for inputs."

**Comment by rickyeasley** [comment]
Hey ozone the cool thing about have been in 6 mental hospitals, when I do
comment suicide I'm going to take a few sons of bitches with me

**Comment by valerio1** [comment]
+1

**Comment by OAGr** [comment]
This is related to this story:
https://github.com/getguesstimate/guesstimate-app/issues/69
