### ISSUE TITLE
Mode to show all inputs

### ISSUE THREAD

**Issue by OAGr** [getguesstimate/guesstimate-app#573]
This should just be a button on the space toolbar

**Comment by mmcdermott** [comment]
Ozzie, the code in this branch: https://github.com/getguesstimate/guesstimate-app/compare/573-show-all-inputs-and-make-view-options-toggles?expand=1 is up to date, defines this option, reworks the view options to be independently togglable within the drop down menu. It needs a new icon for the expanded view option, so I'm assigning it to you for now. If you'd like, I can also move the view menu to be toolbar toggles, in which case just assign it back to me and I'll take care of that as well.
