### ISSUE TITLE
Estimates with variable certainty

### ISSUE THREAD

**Issue by OAGr** [getguesstimate/guesstimate-app#59]
A few people have requested being able to declare their 99% range or similar, instead of their 90% interval.  

I'm thinking this should be implemented by a more detailed 'distribution editor' later on.

**Comment by rickyeasley** [comment]
Hey olé bubbly ozz u know we're harps is by A Chicken, meet me there in 15
mins. u fkg cocksucker

**Comment by OAGr** [comment]
Rated p-low because only one person has asked for it.
