### ISSUE TITLE
Error underneath value field when relevant

### ISSUE THREAD

**Issue by OAGr** [getguesstimate/guesstimate-app#590]
Possible errors:
- Input is not known (or characters)
- Not complete
- Upper bound is lower than lower bound.

**Comment by mmcdermott** [comment]
Any objections to doing this styled like a tooltip? Or did you have something else in mind?

**Comment by OAGr** [comment]
This could be a tooltip.  Not complete means that there's unfinished syntax, like, '=XA +'.

Not sure if that creates an error though.
