### ISSUE TITLE
Bootstrap Navigation Dropdown with Repo List

### ISSUE THREAD

**Issue by OAGr** [getguesstimate/guesstimate-app#6]
![image](https://cloud.githubusercontent.com/assets/377065/9418106/68e605ee-4806-11e5-9623-55eea55173d2.png)

As a user, I should see a bootstrap dropdown list of my models.  See here:
http://react-bootstrap.github.io/components.html

This should go on the top left, next to the + button.

**Comment by haryshwaran** [comment]
Dropdown added, had issues with links not working from the repos page, which was fixed by ozzie, now the dropdown does not close after a click. Issue can be closed after fixing this.
