### ISSUE TITLE
Multiple unreadable models on index page

### ISSUE THREAD

**Issue by OAGr** [getguesstimate/guesstimate-app#60]
Two solutions for now:
1) Clicking the 'create model' link multiple times shouldn't result in multiple models.
2) We should filter out models with less than 1 metric from the main page.

**Comment by davidmanheim** [comment]
This looks like it needs a filter on line 11 of guesstimate-app/src/routes/app.js , where it seems to fetch the models.
I'm unsure how to filter them, since I'm not familiar enough with the object model.
It may also be better to replace the default of "all public models" for the front page.

**Comment by OAGr** [comment]
I fixed some of this in this commit (and the ones around it).
https://github.com/getguesstimate/guesstimate-app/commit/5744d0b3a29d4c2ef2c3aab6efb0cb963d0ca768

Filtered for models with over one metric in them.  Search like that is done with Algolia, which is pretty great but adds some complexity.

**Comment by OAGr** [comment]
This has been addressed by an is_searchable tag, but it would be better if we could even better select the top models.

**Comment by OAGr** [comment]
This has been addressed by an is_searchable tag, but it would be better if we could even better select the top models.
