### ISSUE TITLE
Saving Records / Undo / Checkpoints

### ISSUE THREAD

**Issue by OAGr** [getguesstimate/guesstimate-app#62]
It would be great to restore to previous versions. A user recommended we use a conflict-free replicated data type (CRDT), perhaps with [swarm](https://github.com/gritzko/swarm).  

A few history-related features that would be useful:

- A list of what changed recently, similar to Trello
- Undo
- Manual snapshots
- Save and restore from JSON. (import & export)
- Saving snapshots automatically on the server
- Collaboration

**Comment by boxxxie** [comment]
when you talked to me, you mentioned collaboration. you may want to mention that as a bullet.
if you use CRDTs, you can implement saving on the client.
if you roll your own CRDTs, and are able to represent them as an ordered event log, then you have undo, and you probably have better conflict resolution.

**Comment by OAGr** [comment]
Right now we have undo/redo, plus we are saving checkpoints in the backend on each save.
