### ISSUE TITLE
Top Banner gets mis-sized when I select a cell in chrome

### ISSUE THREAD

**Issue by kuza55** [getguesstimate/guesstimate-app#70]
When I select a cell in chrome the top banner changes height and makes the interface seem a bit broken.

![guesstimate](https://cloud.githubusercontent.com/assets/387986/12224195/0c2c2ee2-b79f-11e5-8337-e59c2fa220b6.png)

I've also noticed that it doesn't load at all when I try to use it in IE11.

**Comment by OAGr** [comment]
I'm having trouble reproducing this issue.  What version of chrome are you using?

Also, not too surprised about IE11.  It will be a bit before I can get things set up to get it working there.

**Comment by kuza55** [comment]
My UA is Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.71 Safari/537.36

FWIW this happens when I double-click on a cell and the name/value inputs show up. I also reproduced this in incognito with all my extensions disabled.

**Comment by mmcdermott** [comment]
Please re-open if this is still present and we'll investigate.
