### ISSUE TITLE
Shortcuts use ctrl instead of cmd on Mac

### ISSUE THREAD

**Issue by michaeldickens** [getguesstimate/guesstimate-app#719]
On Mac, it's standard for cut/copy/paste to use the command key (cmd-x cmd-c cmd-z), but Guesstimate requires using the control key.

**Comment by OAGr** [comment]
It should work with cmd, at least it does for me on my mac.  If it doesn't that's a bug.

**Comment by michaeldickens** [comment]
cmd-X/C/V works on my work computer. Could be a local issue.
