### ISSUE TITLE
Behavior is too dependent on current state

### ISSUE THREAD

**Issue by michaeldickens** [getguesstimate/guesstimate-app#720]
In Excel, I know exactly what's going to happen when I click on a cell. In Guesstimate, clicking and typing does different things depending on what's in focus, and it's hard to tell what's in focus. I keep finding myself clicking on a cell trying to select it, getting an "invalid syntax" error, and then seeing that I inserted a cell name into a formula instead of selecting a cell. I never remember that I have to leave the focus of the cell formula in order to select other cells.

This is one example of the many ways in which Guesstimate behaves differently depending on what's in focus. It makes it hard to figure out/learn how to do anything because the UI's behavior is unpredictable.

**Comment by OAGr** [comment]
Good point, we'll work on refining this.
