### ISSUE TITLE
Default privacy behavior is unexpected

### ISSUE THREAD

**Issue by michaeldickens** [getguesstimate/guesstimate-app#721]
1. It's surprising that models are private by default for premium accounts (especially because they're public by default for non-premium), which made it confusing when I tried to share a model that I had just created.
2. It's surprising that if you create a copy of a public model, the copy is private by default.
3. When a model is private, others should see something saying "this model is private" instead of just seeing nothing.

**Comment by OAGr** [comment]
1 and 2 are a bit of a design decision, but I could understand.  Basically, the logic now goes, 'if the user has access to private models, make everything private'.  We'll reconsider or think of adding some initial creation toggle.

3 is definitely a lack of functionality, i'll file a separate story for that.

**Comment by michaeldickens** [comment]
I can understand the argument for making things private by default since it could be a problem if people create a public model and expect it to be private. Perhaps find a way to make it more obvious whether a model is public or private, such as by doing (3).

**Comment by michaeldickens** [comment]
Maybe have a Share button that copies the URL, but if the model is private then it warns you that the model is private.
