### ISSUE TITLE
Individuals get 3 free private models

### ISSUE THREAD

**Issue by OAGr** [getguesstimate/guesstimate-app#745]
[removed]

**Comment by yalla** [comment]
I'm now a little confused about the definition of 'individuals'. I subscribed to the $5 'Individual plan', which gives me, as of today, 20 private models. In my account settings this is called a "Lite Plan". So what does that mean now, when the title was called "Everyone gets 3 three private models" and now it's called "Individuals get 3 free private models"?

Does that mean that the Lite/Individual $5 plan will be reduced to 3 private models, where it's 20 now or is this just a confusion, that "individual" will be anyone without a subscription?

**Comment by OAGr** [comment]
This task has not been done yet.  The idea was that the 'free' plan would have 3 private models, and the lite one would have 20.  We later decided not to do this, because it would complicate things a lot (with the company plans).  Looking to revise later on.
