### ISSUE TITLE
Markdown page in elev.io docs

### ISSUE THREAD

**Issue by OAGr** [getguesstimate/guesstimate-app#749]
The markdown icon should link to this (in the model description & metric descriptions)

**Comment by mmcdermott** [comment]
How's this one look?
![markdown elev explanation](https://cloud.githubusercontent.com/assets/470751/17788310/dd14354a-6541-11e6-8d50-ed45088195b1.png)

**Comment by OAGr** [comment]
That works, maybe with a link to more information.

**Comment by mmcdermott** [comment]
There is one, it just didn't fit in the screenshot. I'll mark this closed, then.
