### ISSUE TITLE
Subscribe to private model plan, get dropped on page with a button "Create A Private Model" and clicking that button in Safari does nothing

### ISSUE THREAD

**Issue by mmcdermott** [getguesstimate/guesstimate-app#762]

**Comment by yalla** [comment]
If you subscribe to a private plan and simply click on "New Model", you'll see an icon saying "Private", which is the default.

![bildschirmfoto 2016-09-14 um 11 23 36](https://cloud.githubusercontent.com/assets/350047/18506779/d515412c-7a6d-11e6-906d-cb1489b26bd3.png)

Clicking on it gives you the option to set it to public:

![bildschirmfoto 2016-09-14 um 11 24 14](https://cloud.githubusercontent.com/assets/350047/18506796/e0d4fc00-7a6d-11e6-9cc4-f7559f13d47c.png)

**Comment by mmcdermott** [comment]
This has since been fixed.
