### ISSUE TITLE
Public/Private Button

### ISSUE THREAD

**Issue by OAGr** [getguesstimate/guesstimate-app#80]
![image](https://cloud.githubusercontent.com/assets/377065/12874851/8088e0d4-cd91-11e5-8e0e-ec0b3ba3421f.png)

This page needs to look nicer, have a larger button for private/public with explanations.

- [x]  Basic Button
- [x]  Text inside of that, explaining things
- [x]  Grey out private option if they can't access private models.
- [x]  On server, validate if they can make a private model.

**Comment by valerio1** [comment]
Great idea!
