### ISSUE TITLE
Arrows wrongly drawn when nodes have similar names

### ISSUE THREAD

**Issue by yalla** [getguesstimate/guesstimate-app#822]
I have two cells, both begin with the same prefix, one `PCN` and another one `PCN1` (autonaming scheme). However, a subsequent cell, using only `PCN` also has an arrow from node `PCN1` pointing to it. It does not seem to affect the calculation though.

Screenshot:
![screenshot from 2016-09-15 12-45-40](https://cloud.githubusercontent.com/assets/350047/18547305/ffb1378a-7b42-11e6-862e-e3d57e6bd56e.png)

This issue occurs in the production version on the live server.

**Comment by OAGr** [comment]
Eek, thanks for this.

**Comment by mmcdermott** [comment]
Should be fixed now.
