### ISSUE TITLE
Fix autocomplete

### ISSUE THREAD

**Issue by OAGr** [getguesstimate/guesstimate-app#826]
Autocomplete for fact names currently has a few bugs. Play with it and fix what you find.

**Comment by mmcdermott** [comment]
I've found the following bugs:
For valid Fact Name `five`
  * If I've typed `=#f` I see a suggestion `ive` but hitting `enter` reports a sampling error and yields guesstimate expression `#fve`
  * If I tab accept the suggestion, then hit `space` the fact input decorator does not apply (no purple background)
  * If I type `=#f`, hit `backspace` (so the expression now reads `#`) then hit enter (or tab) the metric
      reports a sampling error and shows expression `#ive`.
  * If I type `=#five`, then hit tab, the metric reports a sampling error and yields expression `#fivee`

I recall you seeing a slightly different issue, where tab completion would straight up not actually work? I could not reproduce this issue. If I'm correctly recalling this issues existence, could you try to reproduce and send me steps?

**Comment by OAGr** [comment]
I couldn't reproduce it.
