### ISSUE TITLE
Fact graph doesn't show arrows on large graphs

### ISSUE THREAD

**Issue by OAGr** [getguesstimate/guesstimate-app#828]
Uncaught TypeError: Cannot read property 'row' of undefined

**Comment by mmcdermott** [comment]
Ozzie, if you can verify this is solved in all cases you were observing this previously, then close it, that would be appreciated.

**Comment by OAGr** [comment]
Definitely not solved yet.

**Comment by OAGr** [comment]
This may be addressed by this: https://github.com/getguesstimate/guesstimate-app/pull/849

**Comment by OAGr** [comment]
We may be loosing a few edges, but I think this is good for now.

**Comment by OAGr** [comment]
Closed by https://github.com/getguesstimate/guesstimate-app/pull/869/files
