### ISSUE TITLE
Input facts don't show in cases:

### ISSUE THREAD

**Issue by mmcdermott** [getguesstimate/guesstimate-app#836]
- [x] After you add them to a model.
- [ ] After the model saves.

**Comment by mmcdermott** [comment]
I believe this should be closed by the server change here: https://github.com/getguesstimate/guesstimate-server/pull/173, but can you verify, Ozzie, as I wasn't able to reproduce the 'After the model saves' issue in the first place?

**Comment by OAGr** [comment]
I experimented with it, it seems fine now.
