### ISSUE TITLE
Write fact in sidebar

### ISSUE THREAD

**Issue by OAGr** [getguesstimate/guesstimate-app#842]

**Comment by yalla** [comment]
By the way, what is this fact book anyway? Just the documentation sidebar?

**Comment by OAGr** [comment]
Not quite :)

It's basically the ability to export and import metrics from spaces.  Because of dependency issues, it's proven to be quite tricky.  (It's kind of like having a graph within a graph).  

We're going to be releasing some of this to a few orgs, then later to all orgs with privacy.  Later on, maybe with public functionality.

**Comment by OAGr** [comment]
This is blocked by https://github.com/getguesstimate/guesstimate-app/issues/842
