### ISSUE TITLE
Previously private models which are now public don't show up in public

### ISSUE THREAD

**Issue by yalla** [getguesstimate/guesstimate-app#846]
Hi all,

I created a model which implements the PERT distribution for my own sake and thought it's useful for other people too, so I set the private model to public. However, it doesn't show up anywhere.

* Search term used: `PERT distribution` (and variants)
* Search filter tried: `recommended`, `recent`, `popular`.

https://www.getguesstimate.com/models/7116

I thought it just might take a while until it shows up, but up until now (>12h later) it's still not there.

Not sure if that's a bug or a feature to prevent accidentally exposing confidential data, but I thought I give you a shout.

Alex.

**Comment by OAGr** [comment]
Thanks for pointing this out.

What's happening is that we have a pretty basic algorithm that chooses what to show in the recent public feed.  This was made to rule out lots of the tiny / test / uninteresting models.

Code here:
https://github.com/getguesstimate/guesstimate-server/blob/master/app/models/space.rb#L135

In this case, you're doing what I would consider interesting things, in ways that this algorithm doesn't recognize.  We'll think about this, maybe make a small patch.

**Comment by OAGr** [comment]
This has been taken care of:
https://github.com/getguesstimate/guesstimate-server/pull/174

There is now some issue with the previews, we'll look into this.

![image](https://cloud.githubusercontent.com/assets/377065/18813446/06fc92a0-82af-11e6-9e12-906b898a78eb.png)
