### ISSUE TITLE
What happened to the samples textbox in the distribution view?

### ISSUE THREAD

**Issue by yalla** [getguesstimate/guesstimate-app#847]
In the past I was able to extract (copy&paste) the resulting samples from the expanded distribution view and it's still mentioned on the Github main-page for this project in an animated picture:

![](https://camo.githubusercontent.com/6953aba6d66b3d3bf916c8cbfb04eecca4166110/687474703a2f2f672e7265636f726469742e636f2f666b4437484a6b6e50542e676966)

I found this rather useful for further post-processing in other tools, but it's either gone or I can't find the option. Since the percentiles are gone too, I'm stuck with 98% and 95% conf-intervals with now further means to make up my own eCDF elsewhere.

**Comment by OAGr** [comment]
It was removed with a refactor to the design.  No one else actually asked for it.  May get on this shortly, it may be pretty simple.

**Comment by yalla** [comment]
Thanks for looking into this. The reason why I'm asking for it is that actual people from my organization asked me "what is the raw data for your reasoning?" and I couldn't provide an answer. Guesstimate is pretty useful for ad-hoc modeling, but when real business decisions will me made, I'm taken accountable and I need to be able to provide a proper trail.

I don't think it's necessary to display the data always like in the screenshot, a little button "show data" would be sufficient for people who really need it.

Maybe it all goes away as soon as you add an option to export data as Slurp-files.
