### ISSUE TITLE
Guesstimates in models get copied hundreds of times

### ISSUE THREAD

**Issue by OAGr** [getguesstimate/guesstimate-app#85]
There seems to be a bug where instead of the input field getting saved over the previously saved value, sometimes it gets saved as well as the previously saved value.  Because multiple guesstimates are allowed for one metric, this can mean that one model can get hundreds or thousands of guesstimates, even if there are few models.  This results in gigantic models that basically crash the server.

This should be fixed.

One additional longer-term feature would be the creation of a yaml or json editor, so at least the user can see what is happening and fix it quickly.

**Comment by AanandHQ** [comment]
Thanks for the explanation Ozzie, this makes sense based on data iterations I see when the model loads (e.g. cell values changing). Hope we are able to resolve this issue and add the editor for longer term fixes.

**Comment by OAGr** [comment]
This is where I think the problem is, in the 'CHANGE_GUESSTIMATE' section
https://github.com/getguesstimate/guesstimate-app/blob/master/src/modules/guesstimates/reducer.js#L12

**Comment by AanandHQ** [comment]
Yeah I think you may be right, not sure you are able to fix this from your end? Happy to amend the code from my end if possible/required. However, if a proper fix is possible I'd really appreciate it.

**Comment by OAGr** [comment]
I can fix it, just in the middle of another challenge.  Trying to fix something else before getting to this (some user login issues)

**Comment by AanandHQ** [comment]
Thanks Ozzie! Really cool to see all the updates and fixes happening post-haste. FYI I'm already an adoring fan of Guesstimate 🤓

**Comment by AanandHQ** [comment]
Hi Ozzie,

Sorry to be a pain but still getting the issue, not sure if you were able to attempt a fix?

Many thanks,

Aanand

**Comment by OAGr** [comment]
I spent some time with it, realizing I need to fix a larger issue to ensure
it will work.  Have spent the past bunch of hours trying to figure out the
best way, will get to it tomorrow.

**Comment by AanandHQ** [comment]
No worries Ozzie,

Thanks I’ll wait for you to get back to me before logging in and messing it up any further :)

Best of luck with it man, and if you need code monkey to help out, holla' at me!

Aanand

**Comment by OAGr** [comment]
Hi,

I think this should have fixed the main issue: https://github.com/getguesstimate/guesstimate-app/pull/86

It doesn't fix any old models that have problems.  However, if you can load these into your browser, then edit them, when they get saved then they should be fine.

**Comment by AanandHQ** [comment]
Hi Ozzie,

Gave it a go and its all running much better, hopefully the fix has sorted out the issue on the long-term.

Cheers!

Aanand

**Comment by OAGr** [comment]
Glad to hear!  

I made a similar fix on the server side.  If no one complains about it soon, I'll make that one permanent, waiting to see if anyone will experience issues with it.

**Comment by AanandHQ** [comment]
Great stuff! hopefully you’ll be issue-free from the user-side of things.
