### ISSUE TITLE
Recent screenshots are having errors

### ISSUE THREAD

**Issue by OAGr** [getguesstimate/guesstimate-app#850]
![image](https://cloud.githubusercontent.com/assets/377065/18813385/475a3282-82ad-11e6-809e-d1ab51b0d056.png)

**Comment by OAGr** [comment]
https://www.getguesstimate.com/models
Go to 'recent' models.

**Comment by mmcdermott** [comment]
Images yield error: `{"message":"{\"error\":\"failed to render after disabling plugins, exit code: 50\"}"}`

(go to https://api.urlbox.io/v1/7fdbd83e-b992-46c9-b2b9-cbe6c69cf7f7/30276085389bee0f8a12998dae1fb9a7792d361f/jpg?delay=40000&height=896&quality=90&url=https%3A%2F%2Fwww.getguesstimate.commodels%2F7158%2Fembed&width=1494)

**Comment by mmcdermott** [comment]
This does not appear related to pre-render issues; the metatags are present to social media bots on some of the afflicted models (tested via slack)

**Comment by mmcdermott** [comment]
Fixed.
