### ISSUE TITLE
Sometimes metric card displays seem to break:

### ISSUE THREAD

**Issue by mmcdermott** [getguesstimate/guesstimate-app#914]
On this model, in chrome only, click on one of the distributions on the far left in the big block in the bottom right:
https://www.getguesstimate.com/models/6545?token=rlwHhG2WUYa0a60aZH9pXEs6Xiko0fI2u8WNboFDRUAtOY93GeyEiXhi8itvF6svGRbFDekMXIDM-8AD7i9EtA

and you see this:

![display-bug-small-dists](https://cloud.githubusercontent.com/assets/470751/19531279/f6b27ee6-95eb-11e6-9ec4-4eee5de9c76e.png)

**Comment by mmcdermott** [comment]
So I removed the 'sup' element in favor of a bit of css, on this branch: https://github.com/getguesstimate/guesstimate-app/compare/fix-sub-card?expand=1
but it doesn't fix the issue. @OAGr can you take a look given you spent some time on the previous, similar issue?

**Comment by OAGr** [comment]
Will look at in a few hours.
