### ISSUE TITLE
Guesstimate should be more mobile friendly

### ISSUE THREAD

**Issue by mmcdermott** [getguesstimate/guesstimate-app#95]
From user:
"I would love this jf it were mobile friendly"
"What would make it more mobile friendly"
"It doesn't fit on the screen of my phone"

Phone: iPhone

**Comment by mmcdermott** [comment]
![download_20160222_201654](https://cloud.githubusercontent.com/assets/470751/13241597/61deb282-d9a1-11e5-9a3c-1690e685f60a.png)

**Comment by OAGr** [comment]
I think this is going to take a lot of work to do right, so am ok pushing it off for a while.
