### ISSUE TITLE
undo behaves unexpectedly

### ISSUE THREAD

**Issue by michaeldickens** [getguesstimate/guesstimate-app#957]
"Undo" should undo all actions. But when I click and drag a cell and then hit undo, it does not undo the click-and-drag, instead undoing the previous action.

**Comment by mmcdermott** [comment]
Thanks for reporting this, @michaeldickens. I'm having a bit of trouble reproducing this issue, however; can you provide some more detailed reproduction instructions?

**Comment by michaeldickens** [comment]
I attempted to reproduce but could not. I'm not exactly sure what I did yesterday to encounter this bug but I tried doing something similar today and couldn't reproduce.
