### ISSUE TITLE
Need more demos of possible use cases

### ISSUE THREAD

**Issue by mmcdermott** [getguesstimate/guesstimate-app#96]
Feedback from user.

**Comment by yalla** [comment]
What about this one? http://www.getguesstimate.com/models/4203
I modeled this after a usecase intented to promote the commercial software Minitab, which offers Monte Carlo simulations as well.
(Note: I'm not quite sure if I gave the standard-deviations quite correct, so if anyone's inclined to correct it, say so. Details in the reasoning for the model.)
